"""
Fast transfer-learning training pipeline using pretrained ResNet18.

Freezes the backbone and trains only the final classification layer
on the synthetic wafer dataset generated by generate_synthetic_dataset.py.

Usage:
    python training/train_fast.py
    python training/train_fast.py --epochs 10 --batch-size 16
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

DATASET_DIR = PROJECT_ROOT / "dataset"
CHECKPOINT_DIR = PROJECT_ROOT / "models" / "checkpoints"

CLASSES = ["scratch", "edge_loss", "cluster", "center", "ring", "normal"]
NUM_CLASSES = len(CLASSES)


# ─── Data loaders ────────────────────────────────────────────────────
def get_dataloaders(batch_size: int = 16, image_size: int = 224):
    """Create train and val dataloaders with standard ImageNet transforms."""
    train_transform = transforms.Compose([
        transforms.Resize((image_size, image_size)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(15),
        transforms.ColorJitter(brightness=0.2, contrast=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
    ])

    val_transform = transforms.Compose([
        transforms.Resize((image_size, image_size)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225]),
    ])

    train_dataset = datasets.ImageFolder(
        str(DATASET_DIR / "train"), transform=train_transform
    )
    val_dataset = datasets.ImageFolder(
        str(DATASET_DIR / "val"), transform=val_transform
    )

    print(f"  Train samples: {len(train_dataset)}")
    print(f"  Val samples:   {len(val_dataset)}")
    print(f"  Classes:       {train_dataset.classes}")

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True,
        num_workers=0, pin_memory=True,
    )
    val_loader = DataLoader(
        val_dataset, batch_size=batch_size, shuffle=False,
        num_workers=0, pin_memory=True,
    )

    return train_loader, val_loader, train_dataset.classes


# ─── Model setup ─────────────────────────────────────────────────────
def create_model(num_classes: int, device: str):
    """Load pretrained ResNet18, freeze backbone, replace final layer."""
    model = models.resnet18(pretrained=True)

    # Freeze all backbone layers
    for param in model.parameters():
        param.requires_grad = False

    # Replace final FC layer (trainable)
    model.fc = nn.Linear(model.fc.in_features, num_classes)

    model = model.to(device)
    return model


# ─── Training loop ───────────────────────────────────────────────────
def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    return running_loss / total, correct / total


@torch.no_grad()
def validate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        loss = criterion(outputs, labels)

        running_loss += loss.item() * images.size(0)
        _, predicted = outputs.max(1)
        total += labels.size(0)
        correct += predicted.eq(labels).sum().item()

    return running_loss / total, correct / total


# ─── Main ────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Fast ResNet18 transfer-learning trainer.")
    parser.add_argument("--epochs", type=int, default=10, help="Training epochs (default: 10)")
    parser.add_argument("--batch-size", type=int, default=16, help="Batch size (default: 16)")
    parser.add_argument("--lr", type=float, default=0.001, help="Learning rate (default: 0.001)")
    parser.add_argument("--image-size", type=int, default=224, help="Image size (default: 224)")
    args = parser.parse_args()

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"🚀 Fast ResNet18 Training Pipeline")
    print(f"   Device: {device}")
    print(f"   Epochs: {args.epochs}")
    print(f"   Batch:  {args.batch_size}")
    print(f"   LR:     {args.lr}")
    print()

    # Data
    train_loader, val_loader, class_names = get_dataloaders(
        batch_size=args.batch_size, image_size=args.image_size
    )

    # Model
    model = create_model(num_classes=NUM_CLASSES, device=device)
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"\n  Trainable params: {trainable:,} / {total_params:,} ({100*trainable/total_params:.1f}%)")

    # Loss & optimizer (only FC layer params)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.fc.parameters(), lr=args.lr)

    # Training
    best_val_acc = 0.0
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    checkpoint_path = CHECKPOINT_DIR / "resnet18_fast.pt"

    print(f"\n{'Epoch':>6} | {'Train Loss':>10} | {'Train Acc':>9} | {'Val Loss':>8} | {'Val Acc':>7} | {'Time':>6}")
    print("-" * 65)

    for epoch in range(1, args.epochs + 1):
        t0 = time.time()

        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = validate(model, val_loader, criterion, device)

        elapsed = time.time() - t0

        print(f"  {epoch:4d}  | {train_loss:10.4f} | {train_acc:8.2%} | {val_loss:8.4f} | {val_acc:6.2%} | {elapsed:5.1f}s")

        # Save best
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "best_val_acc": best_val_acc,
                "class_names": class_names,
                "config": {
                    "split_mode": "lot",
                    "loss_name": "CrossEntropyLoss",
                    "num_classes": NUM_CLASSES,
                    "backbone": "resnet18",
                    "frozen_backbone": True,
                },
                "preprocessing": {
                    "input_size": args.image_size,
                    "normalize_mean": [0.485, 0.456, 0.406],
                    "normalize_std": [0.229, 0.224, 0.225],
                },
                "class_names": list(class_names),
            }, checkpoint_path)
            print(f"         ✅ Saved best model (val_acc={best_val_acc:.2%})")

    print(f"\n🏁 Training complete! Best val accuracy: {best_val_acc:.2%}")
    print(f"   Checkpoint: {checkpoint_path}")


if __name__ == "__main__":
    main()
